### ISSUE TITLE
OSError: GLIBC_2.33 not found

### ISSUE THREAD

**Issue by inv03** [krypton-byte/neonize#12]
I encountered an error while running the application. It seems to be related to a missing version of GLIBC (GNU C Library). Below is the traceback of the error:
```bash
Traceback (most recent call last):
  File "/workspaces/WaBOT/main.py", line 2, in <module>
    from src import Runner
  File "/workspaces/WaBOT/src/__init__.py", line 1, in <module>
    from .bot import Runner
  File "/workspaces/WaBOT/src/bot.py", line 2, in <module>
    from neonize.client import NewClient
  File "/workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/__init__.py", line 1, in <module>
    from .client import NewClient
  File "/workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/client.py", line 20, in <module>
    from ._binder import gocode, func_string, func_callback_bytes, func
  File "/workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/_binder.py", line 38, in <module>
    gocode = load_goneonize()
  File "/workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/_binder.py", line 28, in load_goneonize
    raise e
  File "/workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/_binder.py", line 21, in load_goneonize
    gocode = ctypes.CDLL(f"{root_dir}/{generated_name()}")
  File "/home/codespace/.python/current/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /workspaces/WaBOT/.venv/lib/python3.10/site-packages/neonize/neonize-linux-amd64.so)

```

**Environment:**
     - Operating System: Ubuntu 20.04.6 LTS x86_64 
     - Python Version: 3.10

**Comment by krypton-byte** [comment]
It appears that the application is experiencing errors due to a missing GLIBC (GNU C Library) version. Specifically, this application requires version `GLIBC_2.33`, which is not found on your system.

To resolve this issue, you have several options:

1. **Update your Operating System**:
   Update your Ubuntu operating system to a version that includes GLIBC version 2.33 or higher. This may involve upgrading to a newer release of Ubuntu or installing an update if one is available for your current version.

2. **Use Chroot**:
   Another approach is to use a chroot environment. Chroot allows you to run programs or virtualized systems with their own root directory. You can set up a chroot environment with the GLIBC version required to run your application without affecting the rest of the system. This approach can be useful if you cannot update the entire operating system or if you need to isolate dependencies.
