### ISSUE TITLE
Can't Send Sticker

### ISSUE THREAD

**Issue by Eikosa** [krypton-byte/neonize#52]
When I attempt to send a sticker like this, I receive the following error:

(I tried code in the doc)
```python
case "_sticker":
    await client.send_sticker(
        chat,
        "https://user-images.githubusercontent.com/6876788/96633009-d1818000-1318-11eb-9f1d-7f914f4ccb16.gif",
    )
```

```python
22:40:46.936 [Client/Recv DEBUG] <iq from="s.whatsapp.net" id="132.74-17" t="1733341246" type="result"/>[0m
22:40:49.877 [httpx INFO] - HTTP Request: GET https://user-images.githubusercontent.com/6876788/96633009-d1818000-1318-11eb-9f1d-7f914f4ccb16.gif "HTTP/1.1 200 OK"
22:40:49.883 [neonize.utils.log DEBUG] - exc_type: None, exc_value: None, traceback: None
Exception ignored on calling ctypes callback function: <bound method Event.execute of <neonize.aioze.events.Event object at 0x7f1ab294ace0>>
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/neonize/aioze/events.py", line 87, in execute
    loop.run_until_complete(self.list_func[code](self.client, message))
  File "/usr/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/tmp/ipykernel_4078563/738684099.py", line 18, in on_message
  File "/tmp/ipykernel_4078563/738684099.py", line 40, in handler
  File "/usr/local/lib/python3.10/dist-packages/neonize/aioze/client.py", line 883, in send_sticker
    await self.build_sticker_message(file, quoted, name, packname),
  File "/usr/local/lib/python3.10/dist-packages/neonize/aioze/client.py", line 831, in build_sticker_message
    sticker = await ffmpeg.cv_to_webp()
  File "/usr/local/lib/python3.10/dist-packages/neonize/utils/ffmpeg.py", line 256, in cv_to_webp
    await self.call(ffmpeg_command)
  File "/usr/local/lib/python3.10/dist-packages/neonize/utils/ffmpeg.py", line 267, in call
    popen = await asyncio.create_subprocess_shell(
  File "/usr/lib/python3.10/asyncio/subprocess.py", line 205, in create_subprocess_shell
    transport, protocol = await loop.subprocess_shell(
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1631, in subprocess_shell
    raise ValueError("shell must be True")
ValueError: shell must be True
```

**Comment by filso11** [comment]
I'm having the same problem.

`[neonize.utils.log DEBUG] - exc_type: None, exc_value: None, traceback: None`
